runtime: nodejs18

env_variables:
  DB_HOST=db4free.net
  DB_PORT=3306
  DB_USER=felimichalski4
  DB_PASSWORD=110204michalski
  DB_NAME=neon_dev_db
  CLOUDINARY_CLOUD_NAME= dzikwyuta 
  CLOUDINARY_API_KEY= 269424641564721 
  CLOUDINARY_API_SECRET= 8qxdVORgm3z1QDUk4x6ZfPvERKc
  CLOUDINARY_URL=cloudinary://269424641564721:8qxdVORgm3z1QDUk4x6ZfPvERKc@dzikwyuta
  JWT_SECRET=goooooolgle